// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewJSONGetParams creates a new JSONGetParams object
// no default values defined in spec.
func NewJSONGetParams() JSONGetParams {

	return JSONGetParams{}
}

// JSONGetParams contains all the bound params for the Json get operation
// typically these are obtained from a http.Request
//
// swagger:parameters JsonGet
type JSONGetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Return json repo
	  In: query
	*/
	Jsonrepo []string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewJSONGetParams() beforehand.
func (o *JSONGetParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qJsonrepo, qhkJsonrepo, _ := qs.GetOK("jsonrepo")
	if err := o.bindJsonrepo(qJsonrepo, qhkJsonrepo, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindJsonrepo binds and validates array parameter Jsonrepo from query.
//
// Arrays are parsed according to CollectionFormat: "" (defaults to "csv" when empty).
func (o *JSONGetParams) bindJsonrepo(rawData []string, hasKey bool, formats strfmt.Registry) error {

	var qvJsonrepo string
	if len(rawData) > 0 {
		qvJsonrepo = rawData[len(rawData)-1]
	}

	// CollectionFormat:
	jsonrepoIC := swag.SplitByFormat(qvJsonrepo, "")
	if len(jsonrepoIC) == 0 {
		return nil
	}

	var jsonrepoIR []string
	for _, jsonrepoIV := range jsonrepoIC {
		jsonrepoI := jsonrepoIV

		jsonrepoIR = append(jsonrepoIR, jsonrepoI)
	}

	o.Jsonrepo = jsonrepoIR

	return nil
}
