// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Json Data parser",
    "title": "Data Parser",
    "version": "0.1.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/json": {
      "get": {
        "description": "Returns a list of repos from URL",
        "operationId": "JsonGet",
        "parameters": [
          {
            "type": "string",
            "description": "Return json repo",
            "name": "jsonrepo",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the list of repos",
            "schema": {
              "$ref": "#/definitions/jsonrepo"
            }
          },
          "404": {
            "description": "URL not found",
            "schema": {
              "$ref": "#/definitions/errorResponse"
            }
          },
          "500": {
            "description": "Something has gone horribly wrong",
            "schema": {
              "$ref": "#/definitions/errorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "errorResponse": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "jsonrepo": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "full_name": {
            "type": "string"
          },
          "html_url": {
            "type": "string"
          },
          "id": {
            "type": "integer"
          },
          "login": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Json Data parser",
    "title": "Data Parser",
    "version": "0.1.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/json": {
      "get": {
        "description": "Returns a list of repos from URL",
        "operationId": "JsonGet",
        "parameters": [
          {
            "type": "string",
            "description": "Return json repo",
            "name": "jsonrepo",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the list of repos",
            "schema": {
              "$ref": "#/definitions/jsonrepo"
            }
          },
          "404": {
            "description": "URL not found",
            "schema": {
              "$ref": "#/definitions/errorResponse"
            }
          },
          "500": {
            "description": "Something has gone horribly wrong",
            "schema": {
              "$ref": "#/definitions/errorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "errorResponse": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "jsonrepo": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "full_name": {
            "type": "string"
          },
          "html_url": {
            "type": "string"
          },
          "id": {
            "type": "integer"
          },
          "login": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          }
        }
      }
    }
  }
}`))
}
